force-app/main/default/objects/UIT_Import_Event__e/UIT_Import_Event__e.object-meta.xml
<CustomObject>
    <description>Represents data about successfully Imported, imported records and amount of errors</description>
    <label>UIT Import Event</label>
    <pluralLabel>UIT Import Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/UIT_Import_Event__e/fields/errors__c.field-meta.xml
<CustomField>
    <fullName>errors__c</fullName>
    <defaultValue>0</defaultValue>
    <label>errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UIT_Import_Event__e/fields/importedRecords__c.field-meta.xml
<CustomField>
    <fullName>importedRecords__c</fullName>
    <defaultValue>0</defaultValue>
    <label>importedRecords</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UIT_Import_Event__e/fields/importStatus__c.field-meta.xml
<CustomField>
    <fullName>importStatus__c</fullName>
    <defaultValue>&apos;Error&apos;</defaultValue>
    <label>importStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UIT_Import_Event__e/fields/updatedRecords__c.field-meta.xml
<CustomField>
    <fullName>updatedRecords__c</fullName>
    <defaultValue>0</defaultValue>
    <label>updatedRecords</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UIT_User__c/UIT_User__c.object-meta.xml
<CustomObject>
    <label>UIT_User</label>
    <nameField>
        <label>UIT_User Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIT_Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UIT_User__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UIT_User__c/fields/UIT_User_Avatar__c.field-meta.xml
<CustomField>
    <fullName>UIT_User_Avatar__c</fullName>
    <label>UIT_User Avatar</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/UIT_User__c/fields/UIT_User_Email__c.field-meta.xml
<CustomField>
    <fullName>UIT_User_Email__c</fullName>
    <label>UIT_User Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/UIT_User__c/fields/UIT_User_First_Name__c.field-meta.xml
<CustomField>
    <fullName>UIT_User_First_Name__c</fullName>
    <label>UIT_User First Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataImportBatch.cls
global class DataImportBatch implements Database.Batchable<Integer>, Database.Stateful,  Database.AllowsCallouts {
    
    static final String REQUEST_URL = 'https://reqres.in/api/users?page=';
    Integer CURRENT_PAGE = 1;
    ImportResultData resultData = new ImportResultData();

    global Iterable<Integer> start(Database.BatchableContext context) {
        
        Integer[] values = new Integer[0];
        UserWrapClass response = makeCallout(CURRENT_PAGE);
        while(values.size() < response.total_pages) {
            values.add(values.size());
        }
        return values;
    }

    private UserWrapClass makeCallout(Integer pageNumber) {
        Http callout = new Http();

        HttpRequest request = new HttpRequest();
        request.setEndpoint(REQUEST_URL + String.valueOf(pageNumber));
        request.setMethod('GET');

        HttpResponse response = callout.send(request);
        if (response.getStatusCode() == 200) {
            return UserWrapClass.parse(response.getBody());
        } else {
            return null;
        }
    }

    global void execute(Database.BatchableContext context, Integer[] values) {
        List<UIT_User__c> users = new List<UIT_User__c>();
        for (Integer i : values) {
            UserWrapClass response = makeCallout(CURRENT_PAGE);
            if (response != null) {
                List<UserWrapClass.UitUser> wrappedUsers = response.uit_users;
                users.addAll(getUsers(wrappedUsers));
            }
            CURRENT_PAGE++;
        }
        upsertUitUsers(users);
    }

    private List<UIT_User__c> getUsers(List<UserWrapClass.UitUser> wrappedUsers) {
        List<UIT_User__c> users = new List<UIT_User__c>();
        for (UserWrapClass.UitUser userItem : wrappedUsers) {
            users.add(new UIT_User__c(
                Name = userItem.last_name,
                UIT_User_First_Name__c = userItem.first_name,
                UIT_User_Email__c = userItem.email,
                UIT_User_Avatar__c = userItem.avatar,
                External_ID__c = userItem.id
            ));
        }
        return users;
    }

    private void upsertUitUsers(List<UIT_User__c> users) {
        Database.UpsertResult[] results;

        if (users.size() > 0) {
            results = Database.upsert(users, UIT_User__c.Fields.External_ID__c, false);
        }

        if (results.size() != 0) {
            for (Database.UpsertResult resultItem : results) {
                if (resultItem.isSuccess()) {
                    if (resultItem.isCreated()) {
                        resultData.importedRecords ++;
                    } else {
                        resultData.updatedRecords ++;
                    }
                } else {
                    resultData.errors ++;
                }
                
            }
            if (resultData.importedRecords > 0 || resultData.updatedRecords > 0) {
                resultData.importStatus = 'SUCCESS';
            }
        }
    }
    global void finish(Database.BatchableContext context) {
        List<UIT_Import_Event__e> events = new List<UIT_Import_Event__e>();
        events.add(new UIT_Import_Event__e( 
            importedRecords__c = resultData.importedRecords,
            updatedRecords__c = resultData.updatedRecords,
            errors__c = resultData.errors,
            importStatus__c = resultData.importStatus
        ));
        
        EventBus.publish(events);
    }

    private with sharing class ImportResultData {
        public Integer importedRecords = 0;
        public Integer updatedRecords = 0;
        public Integer errors = 0;
        public String importStatus = 'ERROR';
    }
}